# RSpec
require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new

# RuboCop
require 'rubocop/rake_task'
desc 'Run RuboCop on the tasks and lib directory'
RuboCop::RakeTask.new(:rubocop) do |task|
  task.options  = ['--display-cop-names', '--extra-details']
end

# Reek
require 'reek/rake/task'
Reek::Rake::Task.new do |task|
  task.fail_on_error = false
  task.reek_opts     = '--wiki-links --color'
end

# Ruby Critic
require 'rubycritic/rake_task'
RubyCritic::RakeTask.new

# List all tasks by default
Rake::Task[:default].clear if Rake::Task.task_defined?(:default)
task :default do
  puts `rake -T`
end
