source 'https://rubygems.org'

gem 'docker-api', '~> 1.0', require: false
gem 'faraday', '0.11', require: false
gem 'json', '~> 2.0', require: false
gem 'puma', '~> 3.0', require: false
gem 'rack', '~> 2.0', require: false
gem 'rake', '~> 12.0', require: false
gem 'sinatra', '~> 1.0', require: false

group :development do
  gem 'rack-test', '~> 0.0', require: false
  gem 'reek', '~> 4.0', require: false
  gem 'rspec', '~> 3.0', require: false
  gem 'rubocop', '~> 0.0', require: false
  gem 'rubycritic', '~> 3.0', require: false
  gem 'travis', '~> 1.0', require: false
end
