source 'https://rubygems.org'

gem 'faraday', require: false
gem 'json', require: false
gem 'puma', '3.6.0', require: false
gem 'rack-ssl', '1.4.1', require: false
gem 'r10k', '2.4.3', require: false
gem 'sinatra', '1.4.7', require: false

group :development do
  gem 'rack-test', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'travis', require: false
  gem 'travis-lint', require: false
end
