#!/usr/bin/env ruby
# Policy-based auto signing script for Puppet
# https://docs.puppet.com/puppet/latest/reference/ssl_autosign.html#policy-based-autosigning

require 'yaml'
require 'openssl'
require 'aws-sdk-ec2'

# Read CSR
@cert = ARGV[0]
@csr  = OpenSSL::X509::Request.new(STDIN.read)

# Configure AWS SDK
region = ENV['AWS_DEFAULT_REGION'] || 'us-east-1'
Aws.config.update(region: region)

# AWS EC2
def ec2
  Aws::EC2::Resource.new
end

# Configuration
def cfg
  @cfg ||= YAML.load_file(ENV['AUTOSIGN_CFG'] || 'csr_config.yaml')
rescue => error
  STDERR.puts "Could not load the configuration file! (#{error.message})"
  []
end

# Get a list of custom attributes
def atts
  @csr.attributes
rescue => error
  STDERR.puts "Could not read the attributes! (#{error.message})"
  []
end

# Get extensions
def exts
  atts.select { |att| att.oid == 'extReq' }
      .first.value.value.first.value
rescue => error
  STDERR.puts 'Could not find other extensions in the attributes! ' \
    "(#{error.message})"
  []
end

# Read extension value
def ext(oid, name)
  exts.map do |ext|
    if ext.value[0].value.strip == oid
      ext.value[1].value.gsub(/([\x00-\x1f])/, '').strip
    end
  end.compact.first
rescue => error
  STDERR.puts "Could not find '#{name}' in the extension requets! " \
    "(#{error.message})"
  nil
end

# Get challenge password
def challenge_password
  atts.select { |att| att.oid == 'challengePassword' }
      .first.value.value.first.value.strip
rescue => error
  STDERR.puts 'Could not find challengePassword in the custom attributes! ' \
    "(#{error.message})"
  nil
end

# Get instance
def instance_id
  ext('1.3.6.1.4.1.34380.1.1.2', 'pp_instance_id')
end

# Get image_name
def image_name
  ext('1.3.6.1.4.1.34380.1.1.3', 'pp_image_name')
end

# Get project
def project
  ext('1.3.6.1.4.1.34380.1.1.7', 'pp_project')
end

# Get role
def role
  ext('1.3.6.1.4.1.34380.1.1.13', 'pp_role')
end

# Get master password
def master_password
  cfg['challengePassword']
rescue => error
  STDERR.puts 'Could not find \'challengePassword\' in the configuration! ' \
       "(#{error.message})"
  nil
end

# Get project authorized password
def project_password
  cfg[project]['challengePassword']
rescue => error
  STDERR.puts 'Could not find challengePassword in the configuration for ' \
       "project '#{project}'! (#{error.message})"
  nil
end

# Sign if the master password matches
def check_master_password
  master_password && challenge_password == master_password
end

# Sign if the project password matches
def check_project_password
  project_password && challenge_password == project_password
end

# Sign if its a known instance
def check_instances_list
  ec2.instances.map(&:id).include?(instance_id)
rescue => error
  STDERR.puts "Could not get a list of instances (#{error.message})!"
  false
end

# Sign if the base image is known
def check_images_list
  ec2.images(owners: ['self']).map(&:id).include?(image_name)
rescue => error
  STDERR.puts "Could not get a list of images (#{error.message})!"
  false
end

# Authorization
STDERR.puts "Commencing validation for #{@cert}"
if atts.empty?
  STDERR.puts 'Authorization failed! The CSR has no attributes!'
  abort
elsif check_master_password
  STDERR.puts 'Node authorized based on the provided master challengePassword'
elsif check_project_password
  STDERR.puts 'Node authorized based on the provided project challengePassword'
elsif check_instances_list
  STDERR.puts "Node authorized based on instance id (#{instance_id})"
elsif check_images_list
  STDERR.puts "Node authorized based on image id (#{image_name})"
else
  STDERR.puts 'Authorization failed!'
  abort
end
STDERR.puts "Completed validation for #{@cert} - Signing CSR"
